"""initial schema v1.0.0

Revision ID: 7c7f225282c9
Revises: 
Create Date: 2026-05-09 18:15:09.244965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c7f225282c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('customer_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('next_seq', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_number', sa.Integer(), nullable=True),
    sa.Column('externe_kennung', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_customer', sa.Boolean(), nullable=False),
    sa.Column('is_supplier', sa.Boolean(), nullable=False),
    sa.Column('strasse', sa.String(length=200), nullable=True),
    sa.Column('hausnummer', sa.String(length=20), nullable=True),
    sa.Column('plz', sa.String(length=10), nullable=True),
    sa.Column('ort', sa.String(length=100), nullable=True),
    sa.Column('land', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('rechnung_per_email', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('member_since', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('base_fee_override', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('additional_fee_override', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_number')
    )
    op.create_table('dunning_notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('level_snapshot', sa.Integer(), nullable=False),
    sa.Column('name_snapshot', sa.String(length=100), nullable=False),
    sa.Column('print_title_snapshot', sa.String(length=200), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=False),
    sa.Column('new_due_date', sa.Date(), nullable=True),
    sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fee_invoice_item_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_via', sa.String(length=20), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('sent_to', sa.String(length=200), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('doc_path', sa.String(length=500), nullable=True),
    sa.Column('reset_at', sa.DateTime(), nullable=True),
    sa.Column('reset_by_id', sa.Integer(), nullable=True),
    sa.Column('reset_reason', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dunning_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_counters',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('next_seq', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('is_dunning_fee', sa.Integer(), nullable=False),
    sa.Column('dunning_notice_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_number', sa.String(length=50), nullable=True),
    sa.Column('object_type', sa.String(length=50), nullable=False),
    sa.Column('strasse', sa.String(length=200), nullable=True),
    sa.Column('hausnummer', sa.String(length=20), nullable=True),
    sa.Column('plz', sa.String(length=10), nullable=True),
    sa.Column('ort', sa.String(length=100), nullable=True),
    sa.Column('land', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('base_fee_override', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('additional_fee_override', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_number')
    )
    op.create_table('real_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rate')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('water_tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('valid_from', sa.Integer(), nullable=False),
    sa.Column('valid_to', sa.Integer(), nullable=True),
    sa.Column('base_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('base_fee_label', sa.String(length=100), nullable=True),
    sa.Column('additional_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('additional_fee_label', sa.String(length=100), nullable=True),
    sa.Column('price_per_m3', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billing_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('tariff_name', sa.String(length=100), nullable=False),
    sa.Column('tariff_valid_from', sa.Integer(), nullable=True),
    sa.Column('tariff_valid_to', sa.Integer(), nullable=True),
    sa.Column('tariff_base_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tariff_base_fee_label', sa.String(length=100), nullable=True),
    sa.Column('tariff_additional_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tariff_additional_fee_label', sa.String(length=100), nullable=True),
    sa.Column('tariff_price_per_m3', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tariff_notes', sa.Text(), nullable=True),
    sa.Column('invoices_created', sa.Integer(), nullable=False),
    sa.Column('invoices_skipped', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dunning_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('days_after_due', sa.Integer(), nullable=False),
    sa.Column('fee_fixed', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fee_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fee_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fee_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('new_due_days', sa.Integer(), nullable=True),
    sa.Column('print_title', sa.String(length=200), nullable=True),
    sa.Column('email_subject', sa.String(length=200), nullable=True),
    sa.Column('email_body', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_id', 'level', name='uq_policy_level')
    )
    op.create_table('fiscal_years',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_by_id', sa.Integer(), nullable=True),
    sa.Column('is_vat_liable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('property_ownerships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('real_account_year_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('real_account_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('real_account_id', 'year', name='uq_real_account_year')
    )
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('from_real_account_id', sa.Integer(), nullable=False),
    sa.Column('to_real_account_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_user_preferences_user_key')
    )
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_preferences_user_id'), ['user_id'], unique=False)

    op.create_table('water_meters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('meter_number', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('installed_from', sa.Date(), nullable=True),
    sa.Column('installed_to', sa.Date(), nullable=True),
    sa.Column('initial_value', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('eichjahr', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meter_number')
    )
    op.create_table('fiscal_year_reopen_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_id', sa.Integer(), nullable=False),
    sa.Column('reopened_at', sa.DateTime(), nullable=False),
    sa.Column('reopened_by_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('billing_run_id', sa.Integer(), nullable=True),
    sa.Column('period_year', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('doc_path', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('meter_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('reading_date', sa.Date(), nullable=True),
    sa.Column('value', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('consumption', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meter_id', 'year', name='uq_meter_year')
    )
    op.create_table('booking_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('storno_reason', sa.String(length=500), nullable=True),
    sa.Column('storno_date', sa.Date(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('open_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('period_year', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('open_item_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('real_account_id', sa.Integer(), nullable=True),
    sa.Column('storno_of_id', sa.Integer(), nullable=True),
    sa.Column('storno_reason', sa.String(length=500), nullable=True),
    sa.Column('storno_date', sa.Date(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # FK-Constraints separat vermeidet Reihenfolge-Probleme bei zirkulaeren FKs
    op.create_foreign_key('fk_dunning_notices_created_by_id', 'dunning_notices', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key('fk_dunning_notices_fee_invoice_item_id', 'dunning_notices', 'invoice_items', ['fee_invoice_item_id'], ['id'])
    op.create_foreign_key('fk_dunning_notices_invoice_id', 'dunning_notices', 'invoices', ['invoice_id'], ['id'])
    op.create_foreign_key('fk_dunning_notices_reset_by_id', 'dunning_notices', 'users', ['reset_by_id'], ['id'])
    op.create_foreign_key('fk_dunning_notices_stage_id', 'dunning_notices', 'dunning_stages', ['stage_id'], ['id'])
    op.create_foreign_key('fk_invoice_items_account_id', 'invoice_items', 'accounts', ['account_id'], ['id'])
    op.create_foreign_key('fk_invoice_items_dunning_notice_id', 'invoice_items', 'dunning_notices', ['dunning_notice_id'], ['id'])
    op.create_foreign_key('fk_invoice_items_invoice_id', 'invoice_items', 'invoices', ['invoice_id'], ['id'])
    op.create_foreign_key('fk_invoice_items_project_id', 'invoice_items', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('fk_billing_runs_account_id', 'billing_runs', 'accounts', ['account_id'], ['id'])
    op.create_foreign_key('fk_billing_runs_created_by_id', 'billing_runs', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key('fk_dunning_stages_policy_id', 'dunning_stages', 'dunning_policies', ['policy_id'], ['id'])
    op.create_foreign_key('fk_fiscal_years_closed_by_id', 'fiscal_years', 'users', ['closed_by_id'], ['id'])
    op.create_foreign_key('fk_property_ownerships_customer_id', 'property_ownerships', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key('fk_property_ownerships_property_id', 'property_ownerships', 'properties', ['property_id'], ['id'])
    op.create_foreign_key('fk_real_account_year_balances_real_account_id', 'real_account_year_balances', 'real_accounts', ['real_account_id'], ['id'])
    op.create_foreign_key('fk_transfers_created_by_id', 'transfers', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key('fk_transfers_from_real_account_id', 'transfers', 'real_accounts', ['from_real_account_id'], ['id'])
    op.create_foreign_key('fk_transfers_to_real_account_id', 'transfers', 'real_accounts', ['to_real_account_id'], ['id'])
    op.create_foreign_key('fk_water_meters_property_id', 'water_meters', 'properties', ['property_id'], ['id'])
    op.create_foreign_key('fk_fiscal_year_reopen_logs_fiscal_year_id', 'fiscal_year_reopen_logs', 'fiscal_years', ['fiscal_year_id'], ['year'])
    op.create_foreign_key('fk_fiscal_year_reopen_logs_reopened_by_id', 'fiscal_year_reopen_logs', 'users', ['reopened_by_id'], ['id'])
    op.create_foreign_key('fk_invoices_billing_run_id', 'invoices', 'billing_runs', ['billing_run_id'], ['id'])
    op.create_foreign_key('fk_invoices_created_by_id', 'invoices', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key('fk_invoices_customer_id', 'invoices', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key('fk_invoices_property_id', 'invoices', 'properties', ['property_id'], ['id'])
    op.create_foreign_key('fk_meter_readings_created_by_id', 'meter_readings', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key('fk_meter_readings_meter_id', 'meter_readings', 'water_meters', ['meter_id'], ['id'])
    op.create_foreign_key('fk_booking_groups_created_by_id', 'booking_groups', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key('fk_booking_groups_customer_id', 'booking_groups', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key('fk_booking_groups_invoice_id', 'booking_groups', 'invoices', ['invoice_id'], ['id'])
    op.create_foreign_key('fk_open_items_account_id', 'open_items', 'accounts', ['account_id'], ['id'])
    op.create_foreign_key('fk_open_items_created_by_id', 'open_items', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key('fk_open_items_customer_id', 'open_items', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key('fk_open_items_invoice_id', 'open_items', 'invoices', ['invoice_id'], ['id'])
    op.create_foreign_key('fk_bookings_account_id', 'bookings', 'accounts', ['account_id'], ['id'])
    op.create_foreign_key('fk_bookings_created_by_id', 'bookings', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key('fk_bookings_customer_id', 'bookings', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key('fk_bookings_group_id', 'bookings', 'booking_groups', ['group_id'], ['id'])
    op.create_foreign_key('fk_bookings_invoice_id', 'bookings', 'invoices', ['invoice_id'], ['id'])
    op.create_foreign_key('fk_bookings_open_item_id', 'bookings', 'open_items', ['open_item_id'], ['id'])
    op.create_foreign_key('fk_bookings_project_id', 'bookings', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('fk_bookings_real_account_id', 'bookings', 'real_accounts', ['real_account_id'], ['id'])
    op.create_foreign_key('fk_bookings_storno_of_id', 'bookings', 'bookings', ['storno_of_id'], ['id'])



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    op.drop_table('open_items')
    op.drop_table('booking_groups')
    op.drop_table('meter_readings')
    op.drop_table('invoices')
    op.drop_table('fiscal_year_reopen_logs')
    op.drop_table('water_meters')
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_preferences_user_id'))

    op.drop_table('user_preferences')
    op.drop_table('transfers')
    op.drop_table('real_account_year_balances')
    op.drop_table('property_ownerships')
    op.drop_table('fiscal_years')
    op.drop_table('dunning_stages')
    op.drop_table('billing_runs')
    op.drop_table('water_tariffs')
    op.drop_table('users')
    op.drop_table('tax_rates')
    op.drop_table('real_accounts')
    op.drop_table('properties')
    op.drop_table('projects')
    op.drop_table('invoice_items')
    op.drop_table('invoice_counters')
    op.drop_table('dunning_policies')
    op.drop_table('dunning_notices')
    op.drop_table('customers')
    op.drop_table('customer_counters')
    op.drop_table('app_settings')
    op.drop_table('accounts')
    # ### end Alembic commands ###
